services:
  gg-test-node-backend-2:
    build:
      context: .
      target: production
    image: gg-test-node-backend-2
    container_name: gg-test-node-backend-2
    depends_on:
      - gg-test-node-backend-2-postgres
    environment:
      APPINSIGHTS_CLOUDROLE: gg-test-node-backend-2-local
      APPINSIGHTS_CONNECTIONSTRING: ${APPINSIGHTS_CONNECTIONSTRING}

  gg-test-node-backend-2-postgres:
    image: postgres:11.4-alpine
    environment:
      POSTGRES_DB: gg-test-node-backend-2
      POSTGRES_PASSWORD: ppp
      POSTGRES_USERNAME: postgres
